#Data preprocessing

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.17.0'



```
# LINK FOR DATASET: https://archive.ics.uci.edu/dataset/294/combined+cycle+power+plant
```



In [3]:
data = pd.read_excel('/content/data.xlsx')
x = data.iloc[:, :-1].values
y = data.iloc[:,-1].values

FileNotFoundError: [Errno 2] No such file or directory: '/content/data.xlsx'

In [ ]:
print('X = ',x)
print('Y = ',y)

X =  [[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
Y =  [463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [ ]:
print('X_train',X_train)
print('Y_train',Y_train)
print('X_test',X_test)
print('Y_test',Y_test)

X_train [[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
Y_train [473.93 467.87 431.97 ... 459.01 462.72 428.12]
X_test [[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]
Y_test [431.23 460.01 461.14 ... 473.26 438.   463.28]


#Building ANN

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [ ]:
ann.fit(X_train,Y_train,batch_size = 32, epochs =100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 141420.3906
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 933.6462
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 191.8589
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 180.9358
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 172.1306
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 165.1339
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 155.8991
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 140.4650
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 133.2462
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 117.8407
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 107.8589
Epoch 12/100
 69/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 102.0124

In [ ]:
Y_pred = ann.predict(X_test)
print(Y_pred)

In [ ]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_pred,Y_test))

# ANN FOR CONCRETE COMPRESSIVE STRENGTH DATASET


```
# LINK FOR DATASET: https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength
```



In [ ]:
data = pd.read_excel('/content/Concrete_Data.xls')

In [ ]:
data.head()

In [ ]:
new_column_names = ['col' + str(i+1) for i in range(len(data.columns) - 1)] + ['target_col']
data = data.rename(columns=dict(zip(data.columns, new_column_names)))

In [ ]:
data.head()

In [ ]:
x = data.iloc[:, :-1].values
y = data.iloc[:,-1].values

In [ ]:
print('X = ',x)
print('Y = ',y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'elu'))
ann.add(tf.keras.layers.Dense(units = 6,activation = 'elu'))
ann.add(tf.keras.layers.Dense(units = 1))

In [ ]:
ann.compile(optimizer='adam', loss = 'mean_squared_error')

In [ ]:
ann.fit(X_train,Y_train,batch_size= 64,epochs = 150)

In [ ]:
Y_pred = ann.predict(X_test)

In [ ]:
print(Y_pred)

In [ ]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_pred,Y_test))