#Data preprocessing

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.17.0'



```
# LINK FOR DATASET: https://archive.ics.uci.edu/dataset/294/combined+cycle+power+plant
```



In [1]:
data = pd.read_excel('/content/data.xlsx')
x = data.iloc[:, :-1].values
y = data.iloc[:,-1].values

NameError: name 'pd' is not defined

In [ ]:
print('X = ',x)
print('Y = ',y)

X =  [[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
Y =  [463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [ ]:
print('X_train',X_train)
print('Y_train',Y_train)
print('X_test',X_test)
print('Y_test',Y_test)

X_train [[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
Y_train [473.93 467.87 431.97 ... 459.01 462.72 428.12]
X_test [[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]
Y_test [431.23 460.01 461.14 ... 473.26 438.   463.28]


#Building ANN

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [ ]:
ann.fit(X_train,Y_train,batch_size = 32, epochs =100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 141420.3906
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 933.6462
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 191.8589
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 180.9358
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 172.1306
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 165.1339
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 155.8991
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 140.4650
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 133.2462
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 117.8407
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 107.8589
Epoch 12/100
 69/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 102.0124

In [ ]:
Y_pred = ann.predict(X_test)
print(Y_pred)

In [ ]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_pred,Y_test))

# ANN FOR CONCRETE COMPRESSIVE STRENGTH DATASET


```
# LINK FOR DATASET: https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength
```



In [4]:
data = pd.read_excel('/content/Concrete_Data.xls')

In [5]:
data.head()

Cement (component 1)(kg in a m^3 mixture)  \
0                                      540.0   
1                                      540.0   
2                                      332.5   
3                                      332.5   
4                                      198.6   

   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
0                                                0.0       
1                                                0.0       
2                                              142.5       
3                                              142.5       
4                                              132.4       

   Fly Ash (component 3)(kg in a m^3 mixture)  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   

   Water  (component 4)(kg in a m^3 mixture)  \
0                                      162.0   
1                                      162.0   
2                                      228.0   
3                                      228.0   
4                                      192.0   

   Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                                2.5     
1                                                2.5     
2                                                0.0     
3                                                0.0     
4                                                0.0     

   Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                             1040.0      
1                                             1055.0      
2                                              932.0      
3                                              932.0      
4                                              978.4      

   Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
0                                              676.0         28   
1                                              676.0         28   
2                                              594.0        270   
3                                              594.0        365   
4                                              825.5        360   

   Concrete compressive strength(MPa, megapascals)   
0                                         79.986111  
1                                         61.887366  
2                                         40.269535  
3                                         41.052780  
4                                         44.296075

In [6]:
new_column_names = ['col' + str(i+1) for i in range(len(data.columns) - 1)] + ['target_col']
data = data.rename(columns=dict(zip(data.columns, new_column_names)))

In [7]:
data.head()

col1   col2  col3   col4  col5    col6   col7  col8  target_col
0  540.0    0.0   0.0  162.0   2.5  1040.0  676.0    28   79.986111
1  540.0    0.0   0.0  162.0   2.5  1055.0  676.0    28   61.887366
2  332.5  142.5   0.0  228.0   0.0   932.0  594.0   270   40.269535
3  332.5  142.5   0.0  228.0   0.0   932.0  594.0   365   41.052780
4  198.6  132.4   0.0  192.0   0.0   978.4  825.5   360   44.296075

In [8]:
x = data.iloc[:, :-1].values
y = data.iloc[:,-1].values

In [9]:
print('X = ',x)
print('Y = ',y)

X =  [[ 540.     0.     0.  ... 1040.   676.    28. ]
 [ 540.     0.     0.  ... 1055.   676.    28. ]
 [ 332.5  142.5    0.  ...  932.   594.   270. ]
 ...
 [ 148.5  139.4  108.6 ...  892.4  780.    28. ]
 [ 159.1  186.7    0.  ...  989.6  788.9   28. ]
 [ 260.9  100.5   78.3 ...  864.5  761.5   28. ]]
Y =  [79.98611076 61.88736576 40.26953526 ... 23.69660064 32.76803638
 32.40123514]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [11]:
ann = tf.keras.models.Sequential()

In [12]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'elu'))
ann.add(tf.keras.layers.Dense(units = 6,activation = 'elu'))
ann.add(tf.keras.layers.Dense(units = 1))

In [13]:
ann.compile(optimizer='adam', loss = 'mean_squared_error')

In [14]:
ann.fit(X_train,Y_train,batch_size= 64,epochs = 150)

Epoch 1/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 39565.3008
Epoch 2/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26395.1953  
Epoch 3/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16553.4668 
Epoch 4/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11218.0801 
Epoch 5/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7654.1318 
Epoch 6/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6120.0469 
Epoch 7/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4568.3521 
Epoch 8/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3722.3821 
Epoch 9/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2809.9800 
Epoch 10/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2124.1213 
Epoch 11/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2006.6437 
Epoch 12/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1445.7584 
Epoch 13/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1234.3096 
Epoch 14/150
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1040.2598 
Epoch 15/15

In [15]:
Y_pred = ann.predict(X_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step


In [16]:
print(Y_pred)

[[47.960484]
 [31.333073]
 [43.570347]
 [50.351032]
 [32.05341 ]
 [41.26389 ]
 [40.677433]
 [29.899769]
 [48.460712]
 [48.323   ]
 [37.284122]
 [32.668766]
 [35.29427 ]
 [34.173008]
 [47.78829 ]
 [42.7656  ]
 [32.091938]
 [42.247456]
 [48.566196]
 [35.29836 ]
 [39.801136]
 [44.02036 ]
 [27.211384]
 [48.390476]
 [39.584446]
 [39.576267]
 [43.260105]
 [29.949131]
 [42.765568]
 [40.240726]
 [37.6294  ]
 [45.17795 ]
 [34.700596]
 [40.13683 ]
 [40.185886]
 [32.640354]
 [41.088108]
 [31.010578]
 [34.257633]
 [31.13033 ]
 [44.297565]
 [43.431477]
 [35.03896 ]
 [28.718128]
 [43.308628]
 [41.12476 ]
 [42.496418]
 [48.52915 ]
 [44.245182]
 [53.432148]
 [37.506077]
 [39.59743 ]
 [30.328953]
 [37.227177]
 [31.881062]
 [46.50754 ]
 [30.729008]
 [41.53284 ]
 [43.453022]
 [33.70644 ]
 [42.774128]
 [33.1189  ]
 [35.766727]
 [47.154682]
 [34.261784]
 [37.811527]
 [34.486225]
 [26.589115]
 [28.017368]
 [38.610874]
 [28.407627]
 [30.634602]
 [41.300495]
 [38.161427]
 [38.298985]
 [40.437336]
 [35.333958]

In [17]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_pred,Y_test))

204.11055607581935
